### ISSUE TITLE
rules ahh crash

### ISSUE THREAD

**Issue by BlueTheCube** [ApsZoldat/MindustryMappingUtilities#3]
no such method dude
[crash-report-04_18_2024_16_57_12.txt](https://github.com/ApsZoldat/MindustryMappingUtilities/files/15022471/crash-report-04_18_2024_16_57_12.txt)

**Comment by ApsZoldat** [comment]
I. Know.

(already talked about this on discord)

Ok, turning off passive agressive mode: Anuke did some... thing with this dialogs, i need to fix it in PRs first

**Comment by BlueTheCube** [comment]
what kind of prs

**Comment by ApsZoldat** [comment]
This for example https://github.com/Anuken/Mindustry/pull/9665

I will also close this issue once i fix the info buttons through a new PR, so don't worry about it, i leave it open just as a reminder

**Comment by BlueTheCube** [comment]
can you change the old banned blocks and units to this mod's one?

**Comment by ApsZoldat** [comment]
Yes, of course, but it will require some small changes. Do you also need a setting for defining how many columns will be in this dialog's tables? Like, changing it to 8 for "easier navigation"? Currently there is one in my mod, but i think it's pretty useless huh, i'll just let this table take all dialog's width

**Comment by ApsZoldat** [comment]
Ok, i think i'm done, opening a PR now
